version: '3'
services:
  root:
    build: ../root
    image: root
    ports:
      - "9000:9000"
  team1:
    build: ../team_1
    image: team1
    ports:
      - "8087:8087"
  team2:
    build: ../team_2
    image: team2
    ports:
      - "8088:8088"
  team3:
    build: ../team_3
    image: team3
    ports:
      - "8089:8089"
#  tpBuy:
#    build: ../tp/buy
#    image: tpbuy
#    ports:
#      - "8085:8085"
#  tpNav:
#    build: ../tp/nav
#    image: tpnav
#    ports:
#      - "8083:8083"
#  tpDisplayImage:
#    build: ../tp/display-image
#    image: tpdisplayimage
#    ports:
#      - "8082:8082"
#  tpDisplayTicket:
#    build: ../tp/display-ticket
#    image: tpdisplayticket
#    ports:
#      - "8086:8086"
#  tpHome:
#    build: ../tp/home-root
#    image: tphome
#    ports:
#      - "8081:8081"
